package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import model.GameOfLife;

/**
 *
 * @author tadaki
 */
public class DrawPanel extends javax.swing.JPanel implements Runnable {

    private BufferedImage image;
    private final GameOfLife gol;
    private final int n = 256;
    private final double p = 0.5;
    private volatile boolean running = false;
    private final long sleep=200;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
        gol = new GameOfLife(n);
        gol.randomInitialize(p);
    }

    private void initializeImage() {
        int w = this.getPreferredSize().width;
        int h = this.getPreferredSize().height;
        image = new BufferedImage(w, h, BufferedImage.TYPE_INT_BGR);
        Graphics g = image.getGraphics();
        g.setColor(Color.WHITE);
        g.fill3DRect(0, 0, w, h, true);
    }

    private void updateImage(){
        int w = this.getPreferredSize().width;
        Graphics2D g = (Graphics2D)image.getGraphics();
        Color colors[]={Color.WHITE,Color.RED};
        double f = (double)w/n;
        for(int i = 0;i<n;i++){
            for(int j =0;j<n;j++){
                int r = i + n*j;
                int v = gol.getState(r);
                Rectangle2D.Double s=new Rectangle2D.Double(f*i,f*j,f,f);
                g.setColor(colors[v]);
                g.fill(s);
            }
        }
    }
    
    @Override
    public void paintComponent(Graphics g){
        g.drawImage(image, 0, 0, this);
    }
    
    @Override
    public void run() {
        while(running){
            gol.updateState();
            updateImage();
            repaint();
            try {
                Thread.sleep(sleep);
            } catch (InterruptedException ex) {
            }
        }
    }

    public void start() {
        gol.randomInitialize(p);
        initializeImage();
        running = true;
    }

    public void stop() {
        running = false;
    }

    public void saveImage(){
        try {
            javax.imageio.ImageIO.write(image, "png", new File("gol.png"));
        } catch (IOException ex) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
